spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-account-app
    username: postgres
    password: admin
#    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddlAuto: create
    showSql: true
    openInView: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    allow-bean-definition-overriding: true
